### ISSUE TITLE
Please correct the package name and rename the StarterPlugin

### ISSUE THREAD

**Issue by JohnNiang** [wenjing-xin/plugin-artalk#1]
1. Correct the package name
	https://github.com/wenjing-xin/plugin-artalk/blob/49db783db5ed4e3a705b560873ad90fc044bb614/src/main/java/xin/wenjing/halo/StarterPlugin.java#L1
	
	```diff
	- package run.halo.starter; 
	+ package xin.wenjing.halo;
	```
2. Suggest renaming the StarterPlugin to ArtalkPlugin

**Comment by wenjing-xin** [comment]
> 1. Correct the package name
>    https://github.com/wenjing-xin/plugin-artalk/blob/49db783db5ed4e3a705b560873ad90fc044bb614/src/main/java/xin/wenjing/halo/StarterPlugin.java#L1
>    
>    ```diff
>    - package run.halo.starter; 
>    + package xin.wenjing.halo;
>    ```
> 2. Suggest renaming the StarterPlugin to ArtalkPlugin

已修改并发布了新的release

**Comment by JohnNiang** [comment]
Thanks for the quick fix!
