### ISSUE TITLE
使用pix主题安装artalk 评论区插件页面显示多一个null

### ISSUE THREAD

**Issue by KweilinFang** [wenjing-xin/plugin-artalk#3]
使用pix主题安装artalk 评论区插件页面显示多一个null
![微信图片_20240605220024](https://github.com/wenjing-xin/plugin-artalk/assets/63232563/2692a04b-0f0a-4cfe-a5f5-2017664064be)
![微信图片_20240605220016](https://github.com/wenjing-xin/plugin-artalk/assets/63232563/e928a53b-7c92-44b0-bd8b-db5b3caaaf14)

**Comment by wenjing-xin** [comment]
> 使用pix主题安装artalk 评论区插件页面显示多一个null ![微信图片_20240605220024](https://private-user-images.githubusercontent.com/63232563/336870094-2692a04b-0f0a-4cfe-a5f5-2017664064be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1OTY1MDEsIm5iZiI6MTcxNzU5NjIwMSwicGF0aCI6Ii82MzIzMjU2My8zMzY4NzAwOTQtMjY5MmEwNGItMGYwYS00Y2ZlLWE1ZjUtMjAxNzY2NDA2NGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDE0MDMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNjg2OGJkYzgzMzUwMTZkNDAzOGU0ODgzODI0YzVlM2I4ZjliMGM3MDQ4YjcyODc2YWYyZmNkM2Q0OTJkMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vwWFNTl95aw9eHswqs0rEoLlIGPoznt6-p6GUhP3jHI) ![微信图片_20240605220016](https://private-user-images.githubusercontent.com/63232563/336870104-e928a53b-7c92-44b0-bd8b-db5b3caaaf14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1OTY1MDEsIm5iZiI6MTcxNzU5NjIwMSwicGF0aCI6Ii82MzIzMjU2My8zMzY4NzAxMDQtZTkyOGE1M2ItN2M5Mi00NGIwLWJkOGItZGI1YjNjYWFhZjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDE0MDMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MmQzZjZjMTNmYTIzM2RhYTc2Zjk5MzQxNjRhYWIxZWM4YmViMDI2ODdjNTdhNTcwZjNkN2ZjMDk5NGFmOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.shd5gRe5o2qLXQ-wme-ppkO4YLsaTYglodwTbIXFjzI)

麻烦给一下你的站点地址

**Comment by KweilinFang** [comment]
www.yufang.icu发自我的 iPhone在 2024年6月5日，22:04，chuyao ***@***.***> 写道：﻿

使用pix主题安装artalk 评论区插件页面显示多一个null  

麻烦给一下你的站点地址

**Comment by wenjing-xin** [comment]
刚查看了下 你的文章下边和其他页面是没有评论区的，是关了吗？下载最新版本试试
![image](https://github.com/wenjing-xin/plugin-artalk/assets/130843859/986142a0-6247-4fa7-85ea-845c0e2fad78)

**Comment by KweilinFang** [comment]
是的，关闭了






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月6日(星期四) 下午4:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wenjing-xin/plugin-artalk] 使用pix主题安装artalk 评论区插件页面显示多一个null (Issue #3)














 
刚查看了下 你的文章下边和其他页面是没有评论区的，是关了吗？下载最新版本试试

**Comment by wenjing-xin** [comment]
> 是的，关闭了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年6月6日(星期四) 下午4:37 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [wenjing-xin/plugin-artalk] 使用pix主题安装artalk 评论区插件页面显示多一个null (Issue #3) 刚查看了下 你的文章下边和其他页面是没有评论区的，是关了吗？下载最新版本试试 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

有问题再群内可以回复 处理更快一点
