### ISSUE TITLE
太难了上手

### ISSUE THREAD

**Issue by ccshuibuxing** [wenjing-xin/plugin-artalk#4]
配置了完全不生效，也没有过程教学，也不知道怎么验证是否成功，希望作者在配置的时候能加个验证成功或者验证失败

**Comment by wenjing-xin** [comment]
为什么不加入讨论群问问别人怎么配置成功的呢？

**Comment by wenjing-xin** [comment]
或者详细描述下具体是报什么错，这样才能解决你的问题

**Comment by wenjing-xin** [comment]
> 配置了完全不生效，也没有过程教学，也不知道怎么验证是否成功，希望作者在配置的时候能加个验证成功或者验证失败
请参考我编写的最新教程 https://blog.wenjing.xin/archives/DV1kKzJX
