### ISSUE TITLE
适配主题暗黑模式问题

### ISSUE THREAD

**Issue by tuantuanlive** [wenjing-xin/plugin-artalk#5]
![QQ图片20240722104636](https://github.com/user-attachments/assets/de836272-3b0a-4a5f-8366-a611fe89bb62)

![QQ图片20240722104642](https://github.com/user-attachments/assets/e3899a9b-0d30-463c-92aa-3c65cdf6c679)

![微信截图_20240722104702](https://github.com/user-attachments/assets/1f9176c2-6747-4963-9635-a0df961f0032)

如图所示 选择元素类明暗切换模式 刷新缓存之后评论区如图所示

**Comment by wenjing-xin** [comment]
这不是bug，这是一个新特性，如果你填写了 theme=dark 请将明暗模式修改为 `明暗切换属性选择器` ，如果是类名切换器，请修改为 body=dark
